### Array indexing refers to any use of the square brackets ([]) to index array values. There are many options to indexing, which give numpy indexing great power

## Single Element Indexing

In [1]:
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(x[5])

5


**Unlike lists and tuples, numpy arrays support multidimensional indexing for multidimensional arrays. That means that it is not necessary to separate each dimension’s index into its own set of square brackets.**

In [7]:
# let's create an array
x = np.arange(10)

# let's make the array 2 dimensional
x.shape = (2, 5)
x


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# let's try to access array elements
print(x[1, 2]) #7
print(x[0, 2])  #2
print(x[1, 3])  #8

7
2
8


In [7]:
# let's try to get the rows of the array

print(x[0])
print(x[1])

[0 1 2 3 4]
[5 6 7 8 9]


In [11]:
# let's try anther way to access the elements

print(x[0][2])

2


In [10]:
# let's try other indexing options

x = np.arange(20)
print(x[5:11]) #5 6 7 8 9 10 

[ 5  6  7  8  9 10]


In [16]:
x = [1, 2, 3, 4, 5]
x= x[::-1]
x

[5, 4, 3, 2, 1]

In [17]:
x = np.array([1, 2, 3, 4, 5])
print(x[:-3])
print(x[:3])
print(x[-3:])
print(x[3:])

[1 2]
[1 2 3]
[3 4 5]
[4 5]


In [21]:
x = np.array([2, -4, 5, -6, 7, 0])
x = x[x > 0]
x

array([2, 5, 7])

In [32]:
# indexing through values

print(x[x > 2])
print(x[x == 3])
print(x[x >= 2])


[3 4 5]
[3]
[2 3 4 5]


In [37]:
x = [1, 2, 3, 4, 5]
z = (a**2 for a in x)

q = []
for i in z:
    q.append(i)
print(q)

[1, 4, 9, 16, 25]


In [33]:
x = [1, 2, 3, 4, 5]
z = [a/3 for a in x]
z

[0.3333333333333333,
 0.6666666666666666,
 1.0,
 1.3333333333333333,
 1.6666666666666667]